/* CSS Document */
.ui-blocks {list-style:none;margin:0;padding:0;}
.ui-blocks li {width:350px;float:left;margin:0;margin-bottom:10px;padding:0;height:120px;border-bottom:2px solid #d8d8d8;}
.ui-blocks li img {float:left;}
.ui-blocks li div.ui-right-col {display:table-cell;padding:0 10px;}
.ui-blocks li div.ui-right-col p {font-family:Arial, Helvetica, sans-serif;font-size:11px;color:#686868;margin:0;padding:0;padding-bottom:6px;}
.ui-blocks li div.ui-right-col p b {font-size:16px;font-weight:bold;color:#484949;}
.ui-blocks li div.ui-right-col input {font-size:11px;}
